### ISSUE TITLE
Collect data points from Treepedia

### ISSUE THREAD

**Issue by g4brielvs** [DebordProject/research#1]
Voilà our first issue! 

We will start by running [Treepedia](https://github.com/DebordProject/Treepedia_Public) and take from there,

- [ ] Run Treepedia from source
- [ ] Create local dataset
- [ ] Can we run cluster analysis from those data points?

@g4brielvs @illichosky

**Comment by hugopellissari** [comment]
Finally! Awesome. What would be the plan, just run Treepedia to fetch the data points to build a dataset, or we will also run their algorithm to check the canopy coverage as well? 

I was thinking about creating a parallel issue and also fetch OSM data so we can try to get some information around those points, such as street length , speed limit, proximity of farmer's markets, parks, etc. How does that sound?

Besides, maybe we should save all GSV images for now, so if we come up with anything else to use the images, we don't have to spend our API quotas in that. What do you think?

**Comment by g4brielvs** [comment]
@illichosky Absolutely. Feel free to create as many issues as you see fit. 

I've been having a hard time running Treepedia. The code is poorly documented. I created a Dockerfile to make things smoother and I will push it shortly.

> I was thinking about creating a parallel issue and also fetch OSM data so we can try to get some information around those points, such as street length , speed limit, proximity of farmer's markets, parks, etc. How does that sound?

That was my line of thought. Maybe we should try to focus on a MVP. If you can put your effort into it, that would be great!

> Besides, maybe we should save all GSV images for now, so if we come up with anything else to use the images, we don't have to spend our API quotas in that. What do you think?

Certainly. Google Maps will cost us a fortune. I will estimate how much.
